=== ahmedmerzoug/Summer_2018/prj_st2i-web/src/main/resources/uiView/xsd/uiView.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">


	<xsd:simpleType name="intBin">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="intPer">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="100" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="intRow">
		<xsd:restriction base="xsd:int">
			<xsd:enumeration value="10" />
			<xsd:enumeration value="20" />
			<xsd:enumeration value="50" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="align">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="left" />
			<xsd:enumeration value="right" />
			<xsd:enumeration value="center" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="date" />
			<xsd:enumeration value="number" />
			<xsd:enumeration value="link" />
			<xsd:enumeration value="icon" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="typeBoolean">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="true" />
			<xsd:enumeration value="false" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="clause">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="STRING" />
			<xsd:enumeration value="DATE" />
			<xsd:enumeration value="BOOLEAN" />
			<xsd:enumeration value="LONG" />
			<xsd:enumeration value="INTEGER" />
			<xsd:enumeration value="BIGDECIMAL" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="intBinOrder">
		<xsd:simpleContent>
			<xsd:extension base="intBin">
				<xsd:attribute name="order" type="xsd:int" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="dialogPanelRef">
		<xsd:attribute name="clientId" type="xsd:string" use="required" />
		<xsd:attribute name="widgetVar" type="xsd:string" use="required" />
		<xsd:attribute name="fEdit" type="intBin" />
	</xsd:complexType>



	<xsd:element name="uiXmlElementSearch">
		<xsd:complexType>
			<xsd:attribute name="idRech" type="xsd:string" use="required" />
			<xsd:attribute name="label" type="xsd:string" use="required" />
			<xsd:attribute name="labelAr" type="xsd:string" use="required" />
			<xsd:attribute name="typeComposant" type="xsd:string"
				use="required" />
			<xsd:attribute name="columnDB" type="xsd:string" use="required" />
			<xsd:attribute name="clause" type="clause" use="required" />
			<xsd:attribute name="visible" type="xsd:boolean" use="required" />
			<xsd:attribute name="required" type="xsd:boolean" />
			<xsd:attribute name="joinClass" type="xsd:string" />
			<xsd:attribute name="joinColumnSrc" type="xsd:string" />
			<xsd:attribute name="joinColumnDest" type="xsd:string" />
			<xsd:attribute name="negation" type="xsd:boolean" />
			<xsd:attribute name="clauseExist" type="xsd:boolean" />
			<xsd:attribute name="showCheckbox" type="xsd:boolean" />
			<xsd:attribute name="filter" type="xsd:boolean" />
			<xsd:attribute name="showList" type="xsd:boolean" />
			<xsd:attribute name="requiredFirstDate" type="xsd:boolean" />
			<xsd:attribute name="requiredEndtDate" type="xsd:boolean" />
			<xsd:attribute name="scrollHeight" type="xsd:integer" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="uiSearch">
		<xsd:complexType>

			<xsd:choice minOccurs="1" maxOccurs="unbounded">
				<xsd:element ref="uiXmlElementSearch"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="idUiSearch" type="xsd:string" use="required" />
			<xsd:attribute name="tableName" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="uiViewHeaderGroup">
		<xsd:complexType>
			<xsd:choice minOccurs="1" maxOccurs="unbounded">
				<xsd:element ref="uiViewHeader"></xsd:element>
				<xsd:element ref="uiViewHeaderGroup"></xsd:element>
			</xsd:choice>
			<xsd:attribute name="colTitle" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="uiViewHeader">
		<xsd:complexType>
			<xsd:attribute name="colTitle" type="xsd:string" use="required" />
			<xsd:attribute name="columnModel" type="xsd:string" />
			<xsd:attribute name="columnModelAr" type="xsd:string" />
			<xsd:attribute name="colWidth" type="intPer" />
			<xsd:attribute name="fVisible" type="intBin" />
			<xsd:attribute name="fSort" type="intBin" />
			<xsd:attribute name="fFiltered" type="intBin" />
			<xsd:attribute name="fColumnToggler" type="intBin" />
			<xsd:attribute name="align" type="align" />
			<xsd:attribute name="colFooter" type="xsd:string" />
			<xsd:attribute name="type" type="type" />
			<xsd:attribute name="dual" type="xsd:boolean" />
			<xsd:attribute name="tooltip" type="xsd:boolean" />
			<xsd:attribute name="tooltipVal" type="xsd:string" />
			<xsd:attribute name="tooltipCol" type="xsd:string" />
			<xsd:attribute name="escape" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="uiView">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="title" type="xsd:string" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="tabWidth" type="intPer" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="nbRows" type="intRow" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fAdd" type="intBinOrder" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fEdit" type="intBinOrder" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fDelete" type="intBinOrder"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="fRadioBox" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fResizeColumn" type="intBin"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="fCheckBox" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="libEmptyList" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="libEmptyListFiltred" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="withPagination" type="intBin"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="fFiltered" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fColToggler" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="withFooter" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="dialogPanel" type="dialogPanelRef"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="dialogPanelEdit" type="dialogPanelRef"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="fExportCsv" type="intBinOrder"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="fExportPdf" type="intBinOrder"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="exportFileName" type="xsd:string"
					minOccurs="0" maxOccurs="1" />

				<xsd:choice minOccurs="1" maxOccurs="unbounded">
					<xsd:element ref="uiViewHeader"></xsd:element>
					<xsd:element ref="uiViewHeaderGroup"></xsd:element>
					<xsd:element ref="uiSearch" minOccurs="0" maxOccurs="1"></xsd:element>
				</xsd:choice>

			</xsd:choice>
			<xsd:attribute name="id" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="root">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="uiView" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>

		<xsd:unique name="uiViewIdKey">
			<xsd:selector xpath="./uiView" />
			<xsd:field xpath="@id" />
		</xsd:unique>
	</xsd:element>
</xsd:schema>

=== ahmedmerzoug/Summer_2018/prj_st2i-web/target/prj_st2i/WEB-INF/classes/uiView/xml/uiViewAdmin.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xsd/uiView.xsd">

	<uiView id="listProfils">
		<title>adminProfil.datatable.title</title>
		<exportFileName>listeProfils</exportFileName>
		<uiViewHeader colTitle="adminProfil.datatable.column.desApp"
			colWidth="30" dual="true" colFooter="adminProfil.datatable.column.code"/>
		<uiViewHeader colTitle="adminProfil.datatable.column.code"
			colWidth="30" type="link" colFooter="adminProfil.datatable.column.desApp"/>
		<uiViewHeader colTitle="adminProfil.datatable.column.desProfil"
			colWidth="30" dual="true" />
		<uiViewHeader colTitle="adminProfil.datatable.column.desActif"
			colWidth="10" align="center" dual="true" />
	</uiView>

	<uiView id="listUsers">
		<title>adminUser.datatable.title</title>
		<exportFileName>listUtilisateurs</exportFileName>
		<uiViewHeader colTitle="adminUser.datatable.column.login"
			colWidth="15" type="link" />
		<uiViewHeader colTitle="adminUser.datatable.column.name"
			colWidth="30" dual="true" />
		<uiViewHeader colTitle="adminUser.datatable.column.mail"
			colWidth="30" />
		<uiViewHeader colTitle="adminUser.datatable.column.cin"
			colWidth="15" align="center" />
		<uiViewHeader colTitle="adminUser.datatable.column.etat"
			colWidth="10" dual="true" />
	</uiView>

	<uiView id="listUsersForProfil">
		<title>adminUser.datatable.title</title>
		<fAdd>0</fAdd>
		<fEdit>0</fEdit>
		<fDelete>0</fDelete>
		<fCheckBox>1</fCheckBox>
		<fExportCsv>0</fExportCsv>
		<fExportPdf>0</fExportPdf>
		<uiViewHeader colTitle="adminUser.datatable.column.login"
			colWidth="15" type="link" />
		<uiViewHeader colTitle="adminUser.datatable.column.name"
			colWidth="30" dual="true" />
		<uiViewHeader colTitle="adminUser.datatable.column.mail"
			colWidth="30" />
		<uiViewHeader colTitle="adminUser.datatable.column.cin"
			colWidth="15" align="center" />
		<uiViewHeader colTitle="adminUser.datatable.column.etat"
			colWidth="10" dual="true" />
	</uiView>

	<uiView id="listProfilsForUser">
		<title>adminProfil.datatable.title</title>
		<fAdd>0</fAdd>
		<fEdit>0</fEdit>
		<fDelete>0</fDelete>
		<fCheckBox>1</fCheckBox>
		<fExportCsv>0</fExportCsv>
		<fExportPdf>0</fExportPdf>
		<uiViewHeader colTitle="adminProfil.datatable.column.desApp"
			colWidth="33" dual="true" />
		<uiViewHeader colTitle="adminProfil.datatable.column.code"
			colWidth="33" />
		<uiViewHeader colTitle="adminProfil.datatable.column.desProfil"
			colWidth="34" dual="true" />
	</uiView>

	<uiView id="listLogAccess">
		<title>logAccess.datatable.title</title>
		<nbRows>20</nbRows>
		<fAdd>0</fAdd>
		<fDelete>0</fDelete>
		<dialogPanel clientId=":formLogAccess" widgetVar="wLogAccess" />
		<exportFileName>historiqueAcces</exportFileName>
		<uiViewHeader colTitle="logAccess.datatable.column.login"
			colWidth="10" type="link" />
		<uiViewHeader colTitle="logAccess.datatable.column.nom"
			colWidth="10" />
		<uiViewHeader colTitle="logAccess.datatable.column.date"
			colWidth="12" type="date" />
		<uiViewHeader colTitle="logAccess.datatable.column.time"
			colWidth="12" align="center" />
		<uiViewHeader colTitle="logAccess.datatable.column.remoteAdd"
			colWidth="12" />
		<uiViewHeader colTitle="logAccess.datatable.column.browser"
			colWidth="14" />
		<uiViewHeader colTitle="logAccess.datatable.column.fonc"
			colWidth="20" />
		<uiViewHeader colTitle="logAccess.datatable.column.access"
			colWidth="10" align="center" dual="true"/>
	</uiView>

	<uiView id="listLogDataBySession">
		<title>logData.datatable.title</title>
		<fAdd>0</fAdd>
		<fEdit>0</fEdit>
		<fDelete>0</fDelete>
		<withPagination>0</withPagination>
		<exportFileName>historiqueDonnees</exportFileName>
		<uiViewHeader colTitle="logData.datatable.column.login"
			colWidth="20" />
		<uiViewHeader colTitle="logData.datatable.column.nom"
			colWidth="20" />
		<uiViewHeader colTitle="logData.datatable.column.date"
			colWidth="10" type="date" />
		<uiViewHeader colTitle="logData.datatable.column.time"
			colWidth="12" align="center" />
		<uiViewHeader colTitle="logData.datatable.column.remoteAdd"
			colWidth="10" />
		<uiViewHeader colTitle="logData.datatable.column.typeOp"
			colWidth="15" dual="true" />
		<uiViewHeader colTitle="logData.datatable.column.table"
			colWidth="15" />
	</uiView>

	<uiView id="listLogData">
		<title>logData.datatable.title</title>
		<nbRows>20</nbRows>
		<fAdd>0</fAdd>
		<fDelete>0</fDelete>
		<dialogPanel clientId=":formLogData" widgetVar="wLogData" />
		<exportFileName>historiqueDonnees</exportFileName>
		<uiViewHeader colTitle="logData.datatable.column.login"
			colWidth="14" type="link" />
		<uiViewHeader colTitle="logData.datatable.column.nom"
			colWidth="20" />
		<uiViewHeader colTitle="logData.datatable.column.date"
			colWidth="10" type="date" />
		<uiViewHeader colTitle="logData.datatable.column.time"
			colWidth="12" align="center" />
		<uiViewHeader colTitle="logData.datatable.column.remoteAdd"
			colWidth="12" />
		<uiViewHeader colTitle="logData.datatable.column.typeOp"
			colWidth="15" dual="true"/>
		<uiViewHeader colTitle="logData.datatable.column.table"
			colWidth="21" />
	</uiView>

	<uiView id="listProfes">
		<title>profes.datatable.title</title>
		<dialogPanel clientId=":formProfes" widgetVar="wProfes" />
		<exportFileName>listeProfession</exportFileName>
		<uiViewHeader colTitle="profes.datatable.column.cod"
			colWidth="35" type="link" />
		<uiViewHeader colTitle="profes.datatable.column.des"
			colWidth="65" dual="true" />
	</uiView>

</root>
