=== ahmedmerzoug/Summer_2018/prj_st2i-test/target/test-classes/config/app.config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:simpleType name="intBin">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="dataBase">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="MYSQL" />
			<xsd:enumeration value="POSTGRESQL" />
			<xsd:enumeration value="SQLSERVER" />
			<xsd:enumeration value="ORACLE" />
		</xsd:restriction>

	</xsd:simpleType>

	<xsd:simpleType name="pwdLength">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1" />
			<xsd:maxInclusive value="50" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="pwdLevel">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="3" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="dataTablePdfConfig">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="bundle" type="xsd:string" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fAffLine" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fAffDate" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fAffPage" type="intBin" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="footerLeftMsg" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="footerRightMsg" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="headerMsg" type="xsd:string"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="root">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="dataBase" type="dataBase" maxOccurs="1"
					minOccurs="1"></xsd:element>
				<xsd:element name="dataTableValueColomnBundle" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element name="menuValueItemBundle" type="xsd:string"
					minOccurs="0" maxOccurs="1" />
				<xsd:element ref="dataTablePdfConfig" minOccurs="0"
					maxOccurs="1" />
				<xsd:element name="fTraceAccesLog" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="fTraceAccesBase" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="fTraceDataLog" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="fTraceDataBase" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="pwdMinLength" type="pwdLength"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="pwdComplexityLevel" type="pwdLevel"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="enableSecurity" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
				<xsd:element name="enableUnitTest" type="intBin"
					maxOccurs="1" minOccurs="1"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== ahmedmerzoug/Summer_2018/prj_st2i-test/target/test-classes/config/app.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./app.config.xsd">

	<!-- Le nom de la base de données utilisé par la couche persistance -->
		<dataBase>POSTGRESQL</dataBase>
						
	<!-- Le nom de la variable RessourceBundle pour les entêtes des « datatable 
		» -->
	<dataTableValueColomnBundle>com</dataTableValueColomnBundle>

	<!-- Le nom de la variable RessourceBundle pour les libellés des menus -->
	<menuValueItemBundle>com</menuValueItemBundle>


	<!-- Le nom de la variable RessourceBundle et les clés des messages utilisé 
		pour la génération du PDF dans le « datatable » -->
	<dataTablePdfConfig>
		<bundle>msg</bundle>
		<footerLeftMsg>pdf.footer.left</footerLeftMsg>
		<footerRightMsg>pdf.footer.right</footerRightMsg>
		<headerMsg>pdf.header.1</headerMsg>
		<headerMsg>pdf.header.2</headerMsg>
	</dataTablePdfConfig>

	<!-- La configuration de la gestion des logs dans l’application -->
	<fTraceAccesLog>0</fTraceAccesLog>
	<fTraceAccesBase>0</fTraceAccesBase>
	<fTraceDataLog>0</fTraceDataLog>
	<fTraceDataBase>0</fTraceDataBase>
	
	<!-- La gestion de la complexité des mots de passe -->
	<pwdMinLength>1</pwdMinLength>
	<pwdComplexityLevel>0</pwdComplexityLevel>
	
	<!-- L'activation de la sécurité des Urls avec Spring Security -->
	<enableSecurity>1</enableSecurity>
	
	<!-- L'activation du mode des tests unitaires -->
	<enableUnitTest>1</enableUnitTest>
	
</root>

=== ahmedmerzoug/Summer_2018/prj_st2i-web/target/classes/config/app.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./app.config.xsd">

	<!-- Le nom de la base de données utilisé par la couche persistance -->
		<dataBase>POSTGRESQL</dataBase>
			
	<!-- Le nom de la variable RessourceBundle pour les entêtes des « datatable 
		» -->
	<dataTableValueColomnBundle>com</dataTableValueColomnBundle>

	<!-- Le nom de la variable RessourceBundle pour les libellés des menus -->
	<menuValueItemBundle>com</menuValueItemBundle>


	<!-- Le nom de la variable RessourceBundle et les clés des messages utilisé 
		pour la génération du PDF dans le « datatable » -->
	<dataTablePdfConfig>
		<bundle>msg</bundle>
		<urlImageHeader>/resources/images/layout/logo.gif</urlImageHeader>
		<headerMsg>pdf.header.1</headerMsg>
		<headerMsg>pdf.header.2</headerMsg>
		<footerMsg>pdf.footer</footerMsg>
	</dataTablePdfConfig>

	<!-- La configuration de la gestion des logs dans l’application -->
	<fTraceAccesLog>1</fTraceAccesLog>
	<fTraceAccesBase>1</fTraceAccesBase>
	<fTraceDataLog>1</fTraceDataLog>
	<fTraceDataBase>1</fTraceDataBase>
	
	<!-- La gestion de la complexité des mots de passe -->
	<pwdMinLength>1</pwdMinLength>
	<pwdComplexityLevel>0</pwdComplexityLevel>
	
	<!-- L'activation de la sécurité des Urls avec Spring Security -->
	<enableSecurity>1</enableSecurity>
	
	<!-- L'activation du mode développement -->
	<isDevMod>1</isDevMod>
	
</root>
